# https://docs.docker.com/compose/yml/
# Each service defined in docker-compose.yml must specify exactly one of
# image or build. Other keys are optional, and are analogous to their
# docker run command-line counterparts.
#
# As with docker run, options specified in the Dockerfile (e.g., CMD,
# EXPOSE, VOLUME, ENV) are respected by default - you don't need to
# specify them again in docker-compose.yml.
#

pydcm_dev:
  image:  ${CREPO}/pydcm
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./chris_backend:/usr/src/chris_backend
    # - ./FS/local:/hostFS/pfconFS
  volumes_from:
    - dicom_listener
    - chris_dev_files
  ports:
    - "8000:8000"
  links:
    - chris_dev_db:mysql
    - pfcon_service:pfcon
    - pman_service:pman
  labels:
    name: "ChRIS_ultron_backEnd"
    role: "Backend development server"

chris_dev_files:
  image:  alpine
  command: "chmod 777 /usr/users"
  volumes:
    - /usr/users
    - /data
  labels:
    name: "ChRIS_ultron_backEnd feed files"
    role: "Backend development feed files"

dicom_listener:
  image:  fnndsc/dck-dicom-listener
  volumes:
    - /incoming
  ports:
    - "10402:10402"
  labels:
    name: "dicom_listener"
    role: "Dicom listener"


