# https://docs.docker.com/compose/yml/
# Each service defined in docker-compose.yml must specify exactly one of
# image or build. Other keys are optional, and are analogous to their
# docker run command-line counterparts.
#
# As with docker run, options specified in the Dockerfile (e.g., CMD,
# EXPOSE, VOLUME, ENV) are respected by default - you don't need to
# specify them again in docker-compose.yml.
#

pfdcm_dev:
  image:  ${CREPO}/pfdcm
  volumes:
    # - /var/run/docker.sock:/var/run/docker.sock
    - .:/usr/local/pfdcm
  ports:
    - "5015:5015"
  labels:
    name: "DICOM intermediatry server, part of the CHRIS backend."
    role: "DICOM intermediatry server, part of the CHRIS backend."
  command: ["--debug", "--forever", "--httpResponse", "--startlistener"]
